// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://grxnfcefkpxdtkzrkqdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdyeG5mY2Vma3B4ZHRrenJrcWRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ5NTYxMjUsImV4cCI6MjA1MDUzMjEyNX0.YNpxvWx7413tDbmlX6Xz91LcNvkyR2d9_xVq3Tc6Gkk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);